# project:
#   type: website
project:
  output-dir: docs
  type: website

website:
  title: "Philippine Chambault"
  sidebar:
    style: "docked"
    search: true
  navbar:
    left:
      - href: about.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: WARMM_project.qmd
        text: The WARMM project
      - href: analyses.qmd
        text: Analyses
      - href: publications2.qmd
        text: Publications
      - href: conferences.qmd
        text: Conferences
      # - href: outreach.qmd
      #   text: Outreach
      - href: cv.qmd
        text: CV

# editor: visual
        
format:
  html:
    theme: flatly #sandstone #solar # minty
    toc: true
    toc-depth: 1
    lof: true
    lot: true









