---
title: Conferences
---

## 2024
**Chambault**, et al. The development of a non‑invasive biologger to detect fine‑scale thermal responses of
cetaceans". *25th Biennial Conference on the Biology of Marine Mammals*. Oral. In-person attendance. Perth-AUSTRALIA.
  
**Chambault**, et al. The nightscape of the Arctic winter shapes the diving behavior of a marine predator". *BLS8
International Biologging Society*. Oral. In-person attendance. Tokyo-JAPAN.


## 2022
**Chambault**, et al. Ecological trap or favorable habitat? First evidence that immature sea turtles may survive at
their range‑limits in the North‑East Atlantic. *International Sea Turtle Symposium*. Oral. Virtual attendance. 


## 2021
**Chambault**, et al. Narwhals in a sauna. *NAMMCO Working Group on Narwhal in West Greenland*. Oral. In-person attendance. Winnipeg-CANADA.

**Chambault**, et al. Arctic whales in warming waters: demographic and behavioural consequences? *BLS7
International Biologging Society*. Plenary (invited speaker). Virtual attendance. Hawaii-USA.


## 2019
**Chambault**, et al. Sea surface temperature drives narwhals’ movements in the Arctic. *23rd Biennial Conference on the Biology of Marine Mammals* Oral. In-person attendance. Barcelona-SPAIN.


## 2018
**Chambault**, et al. Argos and genetics reveal connecting paths between juvenile and adult habitats in green
turtles. Argos conference. *Collecte Localisation Satellite*. Oral. In-person attendance. Toulouse-FRANCE.


## 2016
**Chambault**, et al. Distribution and diving behavior of the French Guianese sea turtles satellite tracked via
Argos. Argos conference. *Collecte Localisation Satellite*. Oral. In-person attendance. Toulouse-FRANCE.

**Chambault**, et al. The influence of oceanographic features on the foraging behavior of the olive ridley sea turtle
Lepidochelys olivacea along the Guiana coast. *36th Annual Sea turtle Symposium*. Oral. In-person attendance. Lima-PERU. 

**Chambault**, et al. Developmental habitat and migratory pathways: identifying key areas to protect future
breeding green turtles across the Caribbean. *36th Annual Sea turtle Symposium*. Poster. In-person attendance. Lima-PERU. Award for the best Poster.


## 2015
**Chambault**, Dispersal and diving adjustments of green turtles in response to dynamic environmental
conditions during post‑nesting migration. *11th Ecology & Behaviour meeting*. Oral. In-person attendance. Toulouse-FRANCE.

**Chambault**, Post‑nesting migration of green turtles to their foraging grounds: Dispersal and diving
adjustments in response to dynamic environmental conditions. *35th Annual Sea turtle Symposium*. Oral. In-person attendance. Dalaman-TURKEY.

**Chambault**, Migration over the Guyana continental shelf: distribution and diving behavior in relation to
mesoscale features. *35th Annual Sea turtle Symposium*. Poster. In-person attendance. Dalaman-TURKEY.


